//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace UtilityWeb.StringSvc {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StringServiceSoap", Namespace="http://tempuri.org/")]
    public partial class StringService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback reverseStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback toUpperCaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback toLowerCaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLengthOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public StringService() {
            this.Url = global::UtilityWeb.Properties.Settings.Default.UtilityWeb_StringSvc_StringService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event reverseStringCompletedEventHandler reverseStringCompleted;
        
        /// <remarks/>
        public event toUpperCaseCompletedEventHandler toUpperCaseCompleted;
        
        /// <remarks/>
        public event toLowerCaseCompletedEventHandler toLowerCaseCompleted;
        
        /// <remarks/>
        public event GetLengthCompletedEventHandler GetLengthCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/reverseString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string reverseString(string input) {
            object[] results = this.Invoke("reverseString", new object[] {
                        input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void reverseStringAsync(string input) {
            this.reverseStringAsync(input, null);
        }
        
        /// <remarks/>
        public void reverseStringAsync(string input, object userState) {
            if ((this.reverseStringOperationCompleted == null)) {
                this.reverseStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreverseStringOperationCompleted);
            }
            this.InvokeAsync("reverseString", new object[] {
                        input}, this.reverseStringOperationCompleted, userState);
        }
        
        private void OnreverseStringOperationCompleted(object arg) {
            if ((this.reverseStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reverseStringCompleted(this, new reverseStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/toUpperCase", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string toUpperCase(string input) {
            object[] results = this.Invoke("toUpperCase", new object[] {
                        input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void toUpperCaseAsync(string input) {
            this.toUpperCaseAsync(input, null);
        }
        
        /// <remarks/>
        public void toUpperCaseAsync(string input, object userState) {
            if ((this.toUpperCaseOperationCompleted == null)) {
                this.toUpperCaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OntoUpperCaseOperationCompleted);
            }
            this.InvokeAsync("toUpperCase", new object[] {
                        input}, this.toUpperCaseOperationCompleted, userState);
        }
        
        private void OntoUpperCaseOperationCompleted(object arg) {
            if ((this.toUpperCaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.toUpperCaseCompleted(this, new toUpperCaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/toLowerCase", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string toLowerCase(string input) {
            object[] results = this.Invoke("toLowerCase", new object[] {
                        input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void toLowerCaseAsync(string input) {
            this.toLowerCaseAsync(input, null);
        }
        
        /// <remarks/>
        public void toLowerCaseAsync(string input, object userState) {
            if ((this.toLowerCaseOperationCompleted == null)) {
                this.toLowerCaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OntoLowerCaseOperationCompleted);
            }
            this.InvokeAsync("toLowerCase", new object[] {
                        input}, this.toLowerCaseOperationCompleted, userState);
        }
        
        private void OntoLowerCaseOperationCompleted(object arg) {
            if ((this.toLowerCaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.toLowerCaseCompleted(this, new toLowerCaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLength", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetLength(string input) {
            object[] results = this.Invoke("GetLength", new object[] {
                        input});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetLengthAsync(string input) {
            this.GetLengthAsync(input, null);
        }
        
        /// <remarks/>
        public void GetLengthAsync(string input, object userState) {
            if ((this.GetLengthOperationCompleted == null)) {
                this.GetLengthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLengthOperationCompleted);
            }
            this.InvokeAsync("GetLength", new object[] {
                        input}, this.GetLengthOperationCompleted, userState);
        }
        
        private void OnGetLengthOperationCompleted(object arg) {
            if ((this.GetLengthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLengthCompleted(this, new GetLengthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void reverseStringCompletedEventHandler(object sender, reverseStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class reverseStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal reverseStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void toUpperCaseCompletedEventHandler(object sender, toUpperCaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class toUpperCaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal toUpperCaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void toLowerCaseCompletedEventHandler(object sender, toLowerCaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class toLowerCaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal toLowerCaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetLengthCompletedEventHandler(object sender, GetLengthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLengthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLengthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591